### ISSUE TITLE
Failed to create the new note.

### ISSUE THREAD

**Issue by wildernessfamily** [dionmunk/vscode-notes#35]
Hi,
I'm having a little problem with the Notes extension. I installed it on my local VSCode. When I try to create a new note, it states 'Failed to create the new note.' That's it. I'm not sure where to look to find more information on why it was unable to create a new note. I did check the settings of the extension and made sure the storage location was properly set. Any guidance would be greatly appreciated. Thank you.

**Comment by 1021331023** [comment]
I have the same problem in the remote server. And, it fails to list notes by "alt + L"

**Comment by 1021331023** [comment]
I solved this problem when I added a "/" to the end of the "Notes: Notes Location"

**Comment by wildernessfamily** [comment]
@1021331023  Confirmed. I added the "/" and it worked. Thank you Lance!

**Comment by lego9430** [comment]
Same for me, cannot use it: here my package.json if ever of help:

Checked on my setting.json and found the "Notes: Notes Location" with the wrong path. 

Issue, hence, fixed

**Comment by henriquederosapx** [comment]
This problem is coming quite frequently though, and is not just the notes location, because, to me, I made it work after re-selecting the location a few times. But then after creating the first couple files, it stopped working.

I believe this may be associated to an action or another logic that is not clear enough.
